apiVersion: 1

contactPoints:
  - orgId: 1
    name: graph-bridge
    receivers:
      - uid: graph-bridge
        type: webhook
        settings:
          url: http://127.0.0.1:8125/alert
          httpMethod: POST
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: graph-bridge
    group_by: [grafana_folder, alertname]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
